### ISSUE TITLE
Deprecation warning in Ansible 2.7

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-pip#16]
```
TASK [geerlingguy.pip : Ensure pip_install_packages are installed.] ****************************************************
[DEPRECATION WARNING]: Invoking "pip" only once while using a loop via squash_actions is deprecated. Instead of using a
 loop to supply multiple items and specifying `name: {{ item.name | default(item) }}`, please use `name: u'{{ 
pip_install_packages }}'` and remove the loop. This feature will be removed in version 2.11. Deprecation warnings can 
be disabled by setting deprecation_warnings=False in ansible.cfg.
ok: [server] => (item=[u'docker'])
```

**Comment by geerlingguy** [comment]
Still don't know what to do for this.

**Comment by geerlingguy** [comment]
According to some internal chatter, it sounds like the task will still _work_ in 2.11, it just won't 'squash' all the loop items into one execution of the task. So instead of installing like:

`pip install package1===1.2.3 package2===2.3.4`

It would install like:

```
pip install package1===1.2.3
pip install package2===2.3.4
```

If that's the case, this doesn't seem like a big deal to me; the convenience of easy control over all the pip package install parameters (per package) is more important than task execution time (considering most of my playbooks maybe install 2-3 packages total, not hundreds).

**Comment by sivel** [comment]
I don't believe anything needs to be done about this.  I can see ways that this task could be improved, but since it is allowing either a dict/hash/map or just a string, it is probably best written like this instead of complicated filter logic.

The warning is basically stating that squashing the loop into a single invocation of the `pip` module will no longer happen in 2.11. This task will continue working, it may just be slower in the future, as it will invoke `pip` for each item in the loop.

The comment above clarifies some additional things that I was going to add here as well.

**Comment by geerlingguy** [comment]
@sivel thanks for clarifying. I think I'll leave this issue open until 2.11 anyways, just so people bumping into it have a reference point.
